### ISSUE TITLE
Cannot find module '../static/dll/vendor-mainfest.json'

### ISSUE THREAD

**Issue by zhangmz0223** [lcw2004/one#16]
```
➜  one-ui git:(master) ✗ npm run dev

> vue-admin@1.0.0 dev /Users/zhangmz/Example Project/one/one-ui
> node build/dev-server.js

module.js:491
    throw err;
    ^

Error: Cannot find module '../static/dll/vendor-mainfest.json'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/zhangmz/Example Project/one/one-ui/build/webpack.dev.conf.js:25:17)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/zhangmz/Example Project/one/one-ui/build/dev-server.js:15:5)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-admin@1.0.0 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-admin@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zhangmz/.npm/_logs/2017-11-14T05_53_40_052Z-debug.log
```

下载代码后，使用cnpm i 下载完后。

**Comment by lcw2004** [comment]
@zhangmz0223 为了提升速度，将公告的库提取出来作为一个dll文件了。
依次执行下面三个命令就行。
npm install
npm run dll
npm run dev

**Comment by zhangmz0223** [comment]
ok，READEME.md 少了npm run dll 。已经运行了
