### ISSUE TITLE
one-ui 生成dll文件错误

### ISSUE THREAD

**Issue by ghlingjun** [lcw2004/one#29]
```
➜  one-ui git:(master) ✗ npm run dll

> vue-admin@1.0.0 dll /Users/ethan/workspace/labs/one/one-ui
> webpack --config build/webpack.dll.conf.js

module.js:529
    throw err;
    ^

Error: Cannot find module '../config'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/ethan/workspace/labs/one/one-ui/build/utils.js:3:14)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-admin@1.0.0 dll: `webpack --config build/webpack.dll.conf.js`
npm ERR! Exit status 1
```

**Comment by lcw2004** [comment]
@ghlingjun 解决了吗，我这里也没遇到过这个问题。

**Comment by ghlingjun** [comment]
解决了。刚发现是我自己把代码改出问题了 -,-
