### ISSUE TITLE
Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project one-msg: There are test failures.

### ISSUE THREAD

**Issue by zbmwmx** [lcw2004/one#31]
[main] DEBUG org.springframework.core.io.support.PathMatchingResourcePatternResolver - Resolved location pattern [classpath*:com/*.class] to resources []
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.059 sec <<< FAILURE! - in com.lcw.one.main.DemoApplicationTests
initializationError(com.lcw.one.main.DemoApplicationTests)  Time elapsed: 0.008 sec  <<< ERROR!
java.lang.IllegalStateException: Unable to find a @SpringBootConfiguration, you need to use @ContextConfiguration or @SpringBootTest(classes=...) with your test
	at org.springframework.util.Assert.state(Assert.java:70)
	at org.springframework.boot.test.context.SpringBootTestContextBootstrapper.getOrFindConfigurationClasses(SpringBootTestContextBootstrapper.java:202)
	at org.springframework.boot.test.context.SpringBootTestContextBootstrapper.processMergedContextConfiguration(SpringBootTestContextBootstrapper.java:137)
![Uploading error.png…]()

**Comment by zbmwmx** [comment]
这个maven-surefire-plugin 总是在maven install 阶段 不能安装， 导致 相关的工程都不能编译 。求教 如何解决。

**Comment by lcw2004** [comment]
你的错误信息好像是运行测试用例的时候报错了。
你用如下命令跳过测试试一下看看？
maven clean install -Dmaven.test.skip=true

**Comment by zbmwmx** [comment]
恩 跳过测试可以用的
