### ISSUE TITLE
one - mysql(navicat).sql导入db后，启动app报错

### ISSUE THREAD

**Issue by olight** [lcw2004/one#35]
启动时报错，查了原因，似乎是 表字段与实体字段不符
one - mysql(navicat).sql 中的sys_dict为
DROP TABLE IF EXISTS `sys_dict`;
CREATE TABLE `sys_dict` (
  **`id` varchar(64) NOT NULL,**
  **`label` varchar(100) DEFAULT NULL,**
  `value` varchar(100) DEFAULT NULL,
  `type` varchar(100) DEFAULT NULL,
  `description` varchar(100) DEFAULT NULL,
  `sort` int(11) DEFAULT NULL,
  `remarks` varchar(255) DEFAULT NULL,
  `del_flag` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

而实体为

@Entity
@Table(name = "sys_dict")
public class SysDictEO {

    @Id
    @Column(name = "dict_id")
    private String dictId;

    @Basic
    @Column(name = "type")
    private String type;

    @Basic
    @Column(name = "name")
    private String name;

    @Basic
    @Column(name = "remark")
    private String remark;

    @Basic
    @Column(name = "del_flag")
    private Integer delFlag;

有些凌乱了，老铁，给下启动方案？

**Comment by lcw2004** [comment]
额。。。字典这一块后来重构了一下。
等周末的时候我整理一下最新的表和数据。

**Comment by olight** [comment]
似乎解决了。one\one-db-init\src\main\resources\db\mysql 里面的sql跑一遍..好了。

2018-10-19 13:22:52.075 DEBUG 48664 --- [  restartedMain] c.l.o.u.persistence.BaseRepositoryImpl   : HQL [ from SysDictEO d  where d.delFlag = 0 order by type ]
2018-10-19 13:22:52.151 DEBUG 48664 --- [  restartedMain] c.l.o.u.persistence.BaseRepositoryImpl   : HQL [ from SysDictDataEO order by sort ]
2018-10-19 13:22:52.168  INFO 48664 --- [  restartedMain] com.lcw.one.base.config.OneMainStartup   : install system config
2018-10-19 13:22:52.171 DEBUG 48664 --- [  restartedMain] c.l.o.u.persistence.BaseRepositoryImpl   : HQL [from SysConfigEO]
2018-10-19 13:22:52.217  INFO 48664 --- [  restartedMain] com.lcw.one.main.OneMainApplication      : Started OneMainApplication in 35.646 seconds (JVM running for 44.309)
2018-10-19 13:22:52.225  INFO 48664 --- [  restartedMain] com.lcw.one.main.OneMainApplication      : Registry ApplicationContext

-----------------日志定在这里不动了。端口8080好像没有起。这个问题排查中...

**Comment by olight** [comment]
yml端口从18080改为
server:
  port: 8080
启动前端9000
打开login，输入admin、admin。如下报错。

2018-10-19 14:48:47.745  INFO 24388 --- [io-8080-exec-10] com.lcw.one.base.aop.WebInfoAspect       : ---- GET : http://localhost:9000/api/initData
2018-10-19 14:48:47.745  INFO 24388 --- [io-8080-exec-10] com.lcw.one.base.aop.WebInfoAspect       : ---- Http Headers : {authorization=, referer=http://localhost:9000/, RemoteHost=127.0.0.1:50993, cookie=JSESSIONID=F494CEF9C9B7E76D1F935F5E11EA3706; OneId=51435c3d08ad4c82918d1a820933b180, accept-language=zh-CN,zh;q=0.8, host=localhost:9000, connection=close, dnt=1, accept-encoding=gzip, deflate, sdch, br, user-agent=Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 SE 2.X MetaSr 1.0, accept=application/json, text/plain, */*}
2018-10-19 14:48:47.745  INFO 24388 --- [io-8080-exec-10] com.lcw.one.base.aop.WebInfoAspect       : ---- Http Parameters : {}
2018-10-19 14:48:47.745  INFO 24388 --- [io-8080-exec-10] com.lcw.one.base.aop.WebInfoAspect       : ---- Execute Method : com.lcw.one.main.rest.InitRestController.initData
2018-10-19 14:48:47.745  INFO 24388 --- [io-8080-exec-10] com.lcw.one.base.aop.WebInfoAspect       : ---- Execute Arguments : request
2018-10-19 14:48:47.747  INFO 24388 --- [io-8080-exec-10] com.lcw.one.base.utils.LoginUserUtils    : CacheValue: CookieValue[51435c3d08ad4c82918d1a820933b180], UserId[1]
2018-10-19 14:48:47.761 DEBUG 24388 --- [io-8080-exec-10] c.l.o.u.persistence.BaseRepositoryImpl   : HQL [select r from SysRoleEO r, SysUserRoleEO ur where r.id = ur.roleId and ur.userId = ?1 order by r.orderIndex]
2018-10-19 14:48:47.762 DEBUG 24388 --- [io-8080-exec-10] c.l.o.u.persistence.BaseRepositoryImpl   : HQL Param: [1]
2018-10-19 14:48:47.762 DEBUG 24388 --- [io-8080-exec-10] c.l.o.u.persistence.BaseRepositoryImpl   : HQL Filled: [select r from SysRoleEO r, SysUserRoleEO ur where r.id = ur.roleId and ur.userId = '1' order by r.orderIndex]
2018-10-19 14:48:47.772 DEBUG 24388 --- [io-8080-exec-10] c.l.o.u.persistence.BaseRepositoryImpl   : HQL [ select distinct m from SysMenuEO m  where m.delFlag = 0 order by sort ]
2018-10-19 14:48:47.786 DEBUG 24388 --- [io-8080-exec-10] c.l.o.u.persistence.BaseRepositoryImpl   : HQL [select r from SysRoleEO r, SysUserRoleEO ur where r.id = ur.roleId and ur.userId = ?1 order by r.orderIndex]
2018-10-19 14:48:47.786 DEBUG 24388 --- [io-8080-exec-10] c.l.o.u.persistence.BaseRepositoryImpl   : HQL Param: [1]
2018-10-19 14:48:47.786 DEBUG 24388 --- [io-8080-exec-10] c.l.o.u.persistence.BaseRepositoryImpl   : HQL Filled: [select r from SysRoleEO r, SysUserRoleEO ur where r.id = ur.roleId and ur.userId = '1' order by r.orderIndex]
2018-10-19 14:48:47.809 DEBUG 24388 --- [io-8080-exec-10] c.l.o.u.persistence.BaseRepositoryImpl   : HQL [select r from SysRoleEO r, SysUserRoleEO ur where r.id = ur.roleId and ur.userId = ?1 order by r.orderIndex]
2018-10-19 14:48:47.809 DEBUG 24388 --- [io-8080-exec-10] c.l.o.u.persistence.BaseRepositoryImpl   : HQL Param: [1]
2018-10-19 14:48:47.809 DEBUG 24388 --- [io-8080-exec-10] c.l.o.u.persistence.BaseRepositoryImpl   : HQL Filled: [select r from SysRoleEO r, SysUserRoleEO ur where r.id = ur.roleId and ur.userId = '1' order by r.orderIndex]
2018-10-19 14:48:47.830 ERROR 24388 --- [io-8080-exec-10] com.lcw.one.main.aop.WebLogAspect        : null

java.lang.NullPointerException: null
	at com.lcw.one.base.config.GlobalConfig.getBooleanValue(GlobalConfig.java:107) ~[classes/:na]
	at com.lcw.one.base.config.GlobalConfig.getBooleanValue(GlobalConfig.java:111) ~[classes/:na]
	at com.lcw.one.main.rest.InitRestController.listSetting(InitRestController.java:84) ~[classes/:na]
	at com.lcw.one.main.rest.InitRestController.initData(InitRestController.java:58) ~[classes/:na]
	at com.lcw.one.main.rest.InitRestController$$FastClassBySpringCGLIB$$16fd5828.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746) ~[spring-aop-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) [spring-aop-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88) ~[spring-aop-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at com.lcw.one.base.aop.WebInfoAspect.logHttpInfo(WebInfoAspect.java:59) ~[classes/:na]
	at sun.reflect.GeneratedMethodAccessor287.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644) [spring-aop-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633) [spring-aop-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70) [spring-aop-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:174) [spring-aop-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88) ~[spring-aop-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at com.lcw.one.main.aop.WebLogAspect.logHttpInfo(WebLogAspect.java:71) ~[classes/:na]
	at sun.reflect.GeneratedMethodAccessor286.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644) [spring-aop-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633) [spring-aop-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70) [spring-aop-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:174) [spring-aop-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) [spring-aop-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) [spring-aop-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688) [spring-aop-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at com.lcw.one.main.rest.InitRestController$$EnhancerBySpringCGLIB$$f0eef94b.initData(<generated>) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209) [spring-web-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136) [spring-web-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102) [spring-webmvc-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:891) [spring-webmvc-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) [spring-webmvc-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) [spring-webmvc-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991) [spring-webmvc-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925) [spring-webmvc-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974) [spring-webmvc-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:866) [spring-webmvc-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851) [spring-webmvc-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-embed-websocket-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61) [shiro-web-1.4.0-RC2.jar:1.4.0-RC2]
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108) [shiro-web-1.4.0-RC2.jar:1.4.0-RC2]
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137) [shiro-web-1.4.0-RC2.jar:1.4.0-RC2]
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125) [shiro-web-1.4.0-RC2.jar:1.4.0-RC2]
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66) [shiro-web-1.4.0-RC2.jar:1.4.0-RC2]
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449) [shiro-web-1.4.0-RC2.jar:1.4.0-RC2]
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365) [shiro-web-1.4.0-RC2.jar:1.4.0-RC2]
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90) [shiro-core-1.4.0-RC2.jar:1.4.0-RC2]
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83) [shiro-core-1.4.0-RC2.jar:1.4.0-RC2]
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:387) [shiro-core-1.4.0-RC2.jar:1.4.0-RC2]
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362) [shiro-web-1.4.0-RC2.jar:1.4.0-RC2]
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125) [shiro-web-1.4.0-RC2.jar:1.4.0-RC2]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108) [shiro-web-1.4.0-RC2.jar:1.4.0-RC2]
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137) [shiro-web-1.4.0-RC2.jar:1.4.0-RC2]
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125) [shiro-web-1.4.0-RC2.jar:1.4.0-RC2]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at com.lcw.one.util.filter.HttpCacheFilter.doFilter(HttpCacheFilter.java:30) [classes/:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at com.lcw.one.util.filter.OverWriteJSessionIdFilter.doFilter(OverWriteJSessionIdFilter.java:27) [classes/:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) [spring-web-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109) [spring-web-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93) [spring-web-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200) [spring-web-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_181]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]

**Comment by lcw2004** [comment]
@olight 已经更新了最新的脚本。
添加了工程one-db-init用于初始化数据，在这个工程里面配置一下数据库链接，启动这个工程即可初始化数据（暂只支持mysql）。
