### ISSUE TITLE
启动报数据库字段缺失错误

### ISSUE THREAD

**Issue by mailme365** [lcw2004/one#40]
启动后台时报如下字段缺失错误， 发现sys_dict 表中定义的为id 字段，但在SysDictEO Entity 中映射的为dict_id，并且该类中的字段与数据库sys_dict 表都不匹配。

Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'sysdicteo0_.dict_id' in 'field list'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_45]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_45]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_45]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[na:1.8.0_45]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.41.jar:5.1.41]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-java-5.1.41.jar:5.1.41]

**Comment by HuhaStephen** [comment]
这个我也遇到了。

**Comment by lcw2004** [comment]
@mailme365 @HuhaStephen 

简单的在这里答复一下，具体的说明会放到wiki里面。

我新添加了一个工程：one-db-init，用来初始化数据，步骤如下：
1. 准备一个空的数据库（不要准备已经有数据的数据库以防冲突）；
2. 在one-db-init的application.yml中配置数据库链接；
3. 运行one-db-init的OneDbInitApplication类启动工程初始化数据库；
4. 在项目成功启动（无报错）之后，即表示成功初始化了数据库；
5. 关闭one-db-init工程，启动one-main工程。

等wiki写完之后会将document里面的mysql脚本删掉。

**Comment by mailme365** [comment]
多谢，使用该方法成功启动后台
